name: faceparse_research
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.0.1
  - torchvision=0.15.2
  - pytorch-cuda=11.8
  - numpy=1.24.3
  - opencv=4.7.0
  - pillow=9.5.0
  - matplotlib=3.7.1
  - scikit-learn=1.2.2
  - tqdm=4.65.0
  - tensorboard=2.13.0
  - pip
  - pip:
    - albumentations==1.3.1
    - segmentation-models-pytorch==0.3.3
    - einops==0.6.1
    - timm==0.9.2
    - grad-cam==1.4.6
    - seaborn==0.12.2
    - pandas==2.0.2
    - jupyter==1.0.0
    - black==23.3.0
    - pytest==7.3.1
    - pyyaml==6.0
