# environment_swapface.yml
name: swapface2pon_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.0.1
  - torchvision=0.15.2
  - pytorch-cuda=11.8
  - numpy=1.24.3
  - opencv=4.7.0
  - pillow=10.0.0
  - matplotlib=3.7.1
  - scikit-learn=1.2.2
  - tqdm # Relaxed version constraint
  - tensorboard=2.13.0
  - pip
  - pip:
    - gfpgan==1.3.8
    - gradio
    - insightface==0.7.3
    - moviepy>=1.0.3
    - onnx==1.14.0
    - onnxruntime-gpu==1.15.1 # Simplified for Windows
    - opennsfw2==0.10.2
    - protobuf==4.23.4
    - psutil==5.9.5
    - realesrgan==0.3.0
    - tensorflow==2.13.0
    - albumentations==1.3.1
    - segmentation-models-pytorch==0.3.3
    - einops==0.6.1
    - timm==0.9.2
    - grad-cam==1.4.6
    - seaborn==0.12.2
    - pandas==2.0.2
    - jupyter==1.0.0
    - black==23.3.0
    - pytest==7.3.1
    - pyyaml==6.0
    - basicsr==1.4.2
    - facexlib==0.3.0
    - lmdb==1.6.2
    - addict==2.4.0
    - easydict==1.13
    - gdown==5.2.0
    - imageio==2.37.0
    - imageio-ffmpeg==0.6.0
    - ffmpy==0.3.0
    - prettytable==3.16.0
    - proglog==0.1.12
    - qudida==0.0.4
    - websockets==11.0.3
